// src/icons/index.js
// Satu pintu masuk: import { FolderIcon, StarIcon } from '../icons'
export { default as ArchiveIcon } from './ArchiveIcon'
export { default as ArrowIcon } from './ArrowIcon'
export { default as AudioIcon } from './AudioIcon'
export { default as CheckIcon } from './CheckIcon'
export { default as CloseIcon } from './CloseIcon'
export { default as CodeIcon } from './CodeIcon'
export { default as ComputerIcon } from './ComputerIcon'
export { default as DocumentIcon } from './DocumentIcon'
export { default as FolderIcon } from './FolderIcon'
export { default as FullscreenIcon } from './FullscreenIcon'
export { default as ImageIcon } from './ImageIcon'
export { default as LockIcon } from './LockIcon'
export { default as ProgramIcon } from './ProgramIcon'
export { default as StarIcon } from './StarIcon'
export { default as TrashIcon } from './TrashIcon'
export { default as VideoIcon } from './VideoIcon'
